dof-dss/nidirect-drupal

composer.json
config/sync/core.extension.yml
config/sync/nidirect_workflow.auditsettings.yml

Remove nidirect_workflow module and start process of replacing with new nicsdru_workflow module from separate repo

D8 nid 277

---

.circleci/config.yml

Does what it says on the tin :)

Update SSH key fingerprint

---

composer.json
composer.lock
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.page.default.yml
config/sync/core.extension.yml
config/sync/field.field.node.landing_page.layout_builder__layout.yml
config/sync/field.field.node.page.layout_builder__layout.yml
config/sync/field.storage.node.layout_builder__layout.yml
config/sync/layout_builder_modal.settings.yml
config/sync/ultimate_cron.job.layout_builder_cron.yml

Not an exhaustive list of restrictions as we still need to define layouts and blocks etc.

D8 nid 295

---

config/sync/core.date_format.medium_date.yml
config/sync/core.entity_view_display.node.news.default.yml
config/sync/core.entity_view_display.node.news.teaser.yml
config/sync/core.extension.yml
config/sync/views.view.news.yml

Compliments PR in custom code repo: https://github.com/dof-dss/nidirect-site-modules/pull/25

D8NID-192 news config

---

composer.lock
phpcs.sh

- Add DrupalPractice.Objects.StrictSchemaDisabled to ignore list

Update coder module for latest code sniffs.

---

config/sync/block.block.exposedformgp_practicesfind_a_gp.yml
config/sync/core.entity_view_display.node.gp_practice.teaser.yml
config/sync/search_api.index.default_content.yml
config/sync/views.view.gp_practices.yml

Need to swap Bartik config for nidirect theme when that theme is ready

D8NID-194 GP search view, block config and search API config

---

composer.json
composer.lock
config/sync/core.extension.yml

first of a series of requests to start making the theme work - first add & enable the twig tweak contribute module to the code base

add the twig tweak contrib module to the project and enable in config

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/filter.format.basic_html.yml
config/sync/filter.format.full_html.yml
config/sync/noreferrer.settings.yml

This PR adds:
noreferrer contrib module to adapt the link render element, as well as an extra text format filter to ensure any links added are protected against https://www.owasp.org/index.php/Reverse_Tabnabbing

DNID-333 noreferrer link management

---

config/sync/block.block.inpagenavigationblock.yml
config/sync/block.block.views_block__related_content_content_by_theme.yml
config/sync/core.entity_view_display.node.article.full.yml

update config for placement of blocks on article page, also update the full content display to remove the sudo field for the banner - will handle this in other ways

D8NID-136 article page theming

---

config/sync/block.block.mainpagecontent.yml
config/sync/block.block.pagetitle.yml
config/sync/block.block.primaryadminactions.yml
config/sync/block.block.tabs.yml
config/sync/block.block.views_block__site_themes_site_themes_home_page.yml

add the 'site themes home page' view block to the main content region on the home page. Adjust weight of other blocks in the region accordingly.

D8NID-220 - theming homepage

---

composer.json
composer.lock

Update core and contrib modules D8NID-351 & D8NID-352

D8 nid 351

---

composer.json
composer.lock
config/sync/block.block.views_block__site_subtopics_block_1.yml
config/sync/core.extension.yml
config/sync/views.view.site_subtopics.yml

This view makes up the lower part of the page when you click on a taxonomy term like 'Motoring' in D7.
To get it working I needed to install the views_contextual_filters_or module.
This view will not actually be displayed anywhere as yet, I will handle that when I get into the 'Articles by Term' view that is coming next !

Site subtopics

---

README.md
config/sync/views.view.workflow_moderation.yml

Some bug fixes (forgotten after recent workflow renaming) and new section added to README

D8 nid 374

---

config/sync/views.view.content.yml

See related PR:
https://github.com/dof-dss/nicsdru_origins_modules/pull/45

simplify admin/content view and remove moderation states

---

.circleci/config.yml

Combines build + static analysis job to avoid excessive faffing when debugging locally.

Add debug job to ease debugging process

---

config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml

Simple permissions config tweak

D8NID-402 Let anonymous users see published GP entities

---

config/sync/block.block.metofficeweather.yml
config/sync/structure_sync.data.yml

Line 35 of structure_sync.data.yml has 'test' as the value. I've put this as a placeholder to work around a bug in Structure Sync (https://digitaldevelopment.atlassian.net/browse/D8NID-409)

D8NID-408 ~ Met Office Weather block

---

config/sync/views.view.contacts_a_z.yml

As seen at https://www.nidirect.gov.uk/contacts/letter/z

Add no results config for the contacts a-z view display

---

config/sync/block.block.pagetitle.yml

- Dovetails with block render on theme template for these pages.

Render the page title block on taxonomy term pages

---

config/sync/block.block.originssocialsharing.yml
config/sync/core.extension.yml

Place new 'social sharing' block on appropriate content type views

Social sharing

---

composer.lock

Fully updating all repos after correcting licence info.

add latest package releases

---

config/sync/webform.webform.site_feedback.yml

Introduces the `s` query parameter for use in the email handler template (adjusted from default)

D8NID-442 Adjust token parameters from D7

---

composer.json
composer.lock

Without it, the list builder is pretty broken so useless to site admins.

D8 nid 460 landing page duplicates and redirects

---

config/sync/views.view.gp_practices_proximity.yml

Unclear what the semantics are, but it seems to yield better results!

Change sort filter from obscure proximity (form) to plain proximity

---

composer.json
composer.lock

Add patch for https://www.drupal.org/project/webform/issues/3109281:
"Required radios data-msg-required does not match data-webform-required-error when radios are conditionally visible"
Add patch for https://www.drupal.org/project/clientside_validation/issues/3110890:
"Cientside validation errors revert to being output as a label in webform wizard pages with ajax enabled"

Add patches for webform and clientside validation jquery modules

---

config/sync/views.view.site_themes.yml

fix broken class on the site themes view

D8NID-188 - tweak

---

composer.json
composer.lock

Logged issue/patch on webform issue queue - https://www.drupal.org/project/webform/issues/3113160.
Added patch into composer.json

D8NID-497 Webforms: enable enhanced autocomplete attribute values

---

config/sync/editor.editor.basic_html.yml
config/sync/editor.editor.full_html.yml
config/sync/filter.format.basic_html.yml

Add missing styles in CKEditor (and remove heading 5 and 6 and formats menu)

D8 nid 423

---

config/sync/core.entity_view_display.media.document.preview.yml

Shows the filename + thumbnail of the document file

D8NID-536 Reinstate missing view mode for publications

---

.circleci/config.yml
.circleci/drupal.settings.php
.circleci/drupal.vhost

NB: Won't fully work until https://github.com/dof-dss/nidirect-site-modules/pull/123/ is merged and a new release is created.

D8NID-571 Add job for functional tests with JS on config only site

---

config/sync/core.entity_view_display.node.article.full.yml
config/sync/core.entity_view_display.node.publication.full.yml

- Articles: adds the photo field; image style needs to be reviewed/adjusted at a later date.
- Publication: adds the attachment field and fixes the date/time format.

Update display of article and publication full view modes

---

composer.lock

Reverts dof-dss/nidirect-drupal#256
I had to force this update and this has had some unforeseen side effects.

Revert "D8NID-578 ~ Update Core to 8.8.3"

---

composer.json
composer.lock

D8 nid 591

---

config/sync/core.entity_view_display.node.news.full.yml

Add photo field as rendered entity on news Full view mode

D8NID-533: News full view mode: add photo field

---

composer.json
composer.lock
config/sync/core.entity_form_display.node.page.default.yml
config/sync/core.entity_view_display.node.page.default.yml
config/sync/core.entity_view_display.node.page.full.yml
config/sync/core.entity_view_display.node.page.teaser.yml
config/sync/node.type.page.yml

Needs https://github.com/dof-dss/nicsdru_origins_modules/pull/62 to bring it together for a full, clean install from config.
I'm slightly hazy on the specifics but this essentially mirrors a fix applied for origins_toc module in the past and seems to have the desired effect.

Investigate page config disappearance

---

config/sync/filter.format.basic_html.yml

Adds an extra attribute to the permitted list

D8NID-618 Add scope attribute to permitted th element in basic_html profile

---

composer.json
composer.lock
config/sync/node.type.contact.yml

This PR introduces a patch to Core that avoids a broken site in the rare condition field config somehow becomes a little out of kilter with contrib or other custom config.
See https://www.drupal.org/project/drupal/issues/2985882
It also removes the origins toc dependency from the contact content type which otherwise would fail to appear after a silent failure.

D8NID-625 fix toc inconsistency

---

config/sync/block.block.views_block__related_content_content_by_theme.yml

Or recipes, but they were deleted a while back

D8NID-506 Don't show block on publication pages

---

config/sync/search_api.index.default_content.yml

Makes that data searchable from the services page.
Needs a Solr reindex to take effect once deployed.

Add GP + Lead GP first and lastname fields to fulltext index fields

---

config/sync/views.view.media.yml

Preprocessed from nidirect_media.module

Add placeholder field to media listing

---

config/sync/core.extension.yml

Run before https://github.com/dof-dss/nidirect-drupal/pull/319

Disable redundant modules

---

config/sync/core.entity_form_display.node.feature.default.yml
config/sync/core.entity_view_display.node.application.default.yml
config/sync/core.entity_view_display.node.application.teaser.yml
config/sync/core.entity_view_display.node.article.default.yml
config/sync/core.entity_view_display.node.article.teaser.yml
config/sync/core.entity_view_display.node.contact.default.yml
config/sync/core.entity_view_display.node.contact.full.yml
config/sync/core.entity_view_display.node.contact.teaser.yml
config/sync/core.entity_view_display.node.driving_instructor.default.yml
config/sync/core.entity_view_display.node.driving_instructor.full.yml
config/sync/core.entity_view_display.node.driving_instructor.teaser.yml
config/sync/core.entity_view_display.node.embargoed_publication.default.yml
config/sync/core.entity_view_display.node.embargoed_publication.teaser.yml
config/sync/core.entity_view_display.node.external_link.default.yml
config/sync/core.entity_view_display.node.featured_content_list.default.yml
config/sync/core.entity_view_display.node.featured_content_list.full.yml
config/sync/core.entity_view_display.node.gp_practice.default.yml
config/sync/core.entity_view_display.node.gp_practice.full.yml
config/sync/core.entity_view_display.node.health_condition.default.yml
config/sync/core.entity_view_display.node.health_condition.teaser.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.full.yml
config/sync/core.entity_view_display.node.landing_page.teaser.yml
config/sync/core.entity_view_display.node.page.default.yml
config/sync/core.entity_view_display.node.page.teaser.yml
config/sync/core.entity_view_display.node.publication.default.yml
config/sync/core.entity_view_display.node.publication.teaser.yml

Remove moderation control widget from all displays now that moderation sidebar has been introduced.

D8 nid 659

---

config/sync/views.view.gp_practices.yml
config/sync/views.view.gp_practices_proximity.yml

Alters "GP practices: by proximity" view to list practice GPs and restructures html output, adds classes, etc + small change to the search label in the standard GP practice view.

D8NID-700 GP Practices - use my location view theming

---

config/sync/views.view.news.yml

Exclusions now fed in as context argument from nidirect_news.module

Skip offset in lower block

---

config/sync/views.view.news.yml

Fix latest news block view to wrap date-published in span with class

---

composer.json
composer.lock

See the list of updates and comments here: https://digitaldevelopment.atlassian.net/browse/D8NID-739

D8 nid 739

---

.platform.app.yaml
.platform/services.yaml
config/sync/core.extension.yml
migrate-fetch.sh
migrate-unpack.sh
web/sites/default/settings.platformsh.php

I don't think there's any harm in these being enabled by default until we're ready to go live. Open to suggestions, either way!

D8NID-796 migrations on psh

---

config/sync/block_blacklist.settings.yml
config/sync/block_content.type.video_and_caption.yml
config/sync/core.entity_form_display.block_content.video_and_caption.default.yml
config/sync/core.entity_view_display.block_content.video_and_caption.default.yml
config/sync/core.entity_view_display.node.landing_page.full.yml
config/sync/core.extension.yml
config/sync/field.field.block_content.video_and_caption.body.yml
config/sync/field.field.block_content.video_and_caption.field_caption.yml
config/sync/field.field.block_content.video_and_caption.field_video.yml
config/sync/field.field.block_content.video_and_caption.field_video_caption_display.yml
config/sync/field.storage.block_content.field_caption.yml
config/sync/field.storage.block_content.field_video.yml
config/sync/field.storage.block_content.field_video_caption_display.yml
config/sync/language.content_settings.block_content.video_and_caption.yml
config/sync/user.role.admin_user.yml
config/sync/user.role.editor_user.yml

- Remove block black list settings relating to layout builder (conflict with layout builder restrictions)
- Config for video and caption custom block type
- Enable layout builder restrictions by region module: gives fine grained control over which blocks can be added to which region
- Permissions: enable editors and admins to create and edit custom blocks used in layout builder

Landing page layout builder

---

config/sync/views.view.news.yml

Allows us to add a convenience link in nidirect_news.module
Relates to https://github.com/dof-dss/nidirect-site-modules/pull/199

Add placeholder region to views header

---

composer.json
composer.lock
config/sync/system.file.yml

Add a patch + config option to transliterate uploaded filenames.

D8NID-832 files transliteration

---

config/sync/views.view.contacts.yml

D8NID-835 Reduce min word length to 2 to aid in capture of short phrases

---

.circleci/config.yml

Missed the obvious on the first command: it was missing the project and environment parameters so the later commands were never reached.

Circle ci fix solr rebuild

---

config/sync/core.entity_form_display.taxonomy_term.site_themes.default.yml
config/sync/core.entity_view_display.taxonomy_term.site_themes.default.yml
config/sync/core.entity_view_display.taxonomy_term.site_themes.full.yml
config/sync/field.field.taxonomy_term.site_themes.field_theme_summary.yml
config/sync/field.storage.taxonomy_term.field_theme_summary.yml

Requires migration rollback before coming into effect or config import will fail

Change field_theme_summary to long, plaintext field

---

composer.json
composer.lock

This will require https://github.com/dof-dss/nidirect-site-modules/pull/226 for compatibility

D8NID-866 ~ Update LinkIt to version 6

---

composer.json
composer.lock

- Uses new semver convention
- 2.x releases are D9 compatible
See https://www.drupal.org/project/whatlinkshere/issues/3170183 for details

D8NID-864 Update whatlinkshere module.

---

composer.json
composer.lock

Now matches how the CI is checking code

Update coder and dependencies

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/views.view.gp_list.yml
config/sync/views.view.gp_practice_list.yml
config/sync/views.view.gp_practices.yml

Replacement for https://github.com/dof-dss/nidirect-drupal/pull/430 which has been approved

D8 nid 354

---

config/sync/views.view.health_conditions.yml

- Set search intro message.
- Change title

Config changes to health conditions view:

---

composer.lock

See https://github.com/zaporylie/composer-drupal-optimizations/pull/22 for details

Fix upstream composer issue.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/metatag.settings.yml

Patch isn't fully stable with 2.1 release, causing fatal exceptions in other parts of the build

Remove schema metatags for medical conditions

---

config/sync/views.view.popular_content.yml

Relates to https://github.com/dof-dss/nidirect-site-modules/pull/267

Hide the block content if there are no results

---

config/sync/core.entity_form_display.node.health_condition.default.yml
config/sync/core.entity_form_display.node.publication.default.yml
config/sync/core.entity_view_display.node.health_condition.default.yml
config/sync/core.entity_view_display.node.health_condition.diff.yml
config/sync/core.entity_view_display.node.health_condition.search_result.yml
config/sync/core.entity_view_display.node.health_condition.teaser.yml
config/sync/editor.editor.basic_html.yml
config/sync/editor.editor.full_html.yml
config/sync/linkit.linkit_profile.default.yml
config/sync/node.type.article.yml
config/sync/node.type.feature.yml
config/sync/node.type.featured_content_list.yml
config/sync/node.type.health_condition.yml
config/sync/node.type.news.yml
config/sync/node.type.page.yml
config/sync/system.performance.yml
config/sync/webform.webform.contact.yml
config/sync/webform.webform.contact_the_make_the_call_team.yml
config/sync/webform.webform.debt_management_enquiry.yml
config/sync/webform.webform.landlord_direct_payments.yml
config/sync/webform.webform.proni_submit_an_enquiry.yml
config/sync/webform.webform.site_feedback.yml
config/sync/webform.webform.state_pension_online_feedback.yml
config/sync/webform.webform.taxi_driver_theory_practice_1.yml
config/sync/webform.webform.taxi_driver_theory_practice_2.yml
config/sync/webform.webform.taxi_driver_theory_practice_3.yml
config/sync/webform.webform.taxi_driver_theory_practice_4.yml
config/sync/webform.webform.year_10_subject_choices_quiz.yml

Some care taken to avoid config changes that were affected by multi-line config or similar red-herrings which run on local environments.

Config flush from master

---

composer.json
composer.lock

Lazy loader placeholders can cause problems here without it.

Add patch to allow us to check for empty template variables

---

composer.json
composer.lock

Ensures when drush cim is executed, it only needs to be run once for the local profile to be detected and applied.

Update config_split module to fix split profile discovery issue

---

config/sync/views.view.popular_content.yml

Increase depth to max and include Application nodes

Adjust popular content view

---

config/sync/core.entity_view_display.node.health_condition.default.yml

Fixes issue with thin banner showing as a link on health conditions rather than as a rendered image.

D8 nid 999

---

config/sync/workflows.workflow.nics_editorial_workflow.yml

- changes made to workflow transitions as specified in ticket
- relates to https://github.com/dof-dss/nicsdru_origins_modules/pull/117

D8NID-1007

---

config/sync/views.view.site_themes.yml

- remove summary field
- remove term name link field and replace with plain term name

D8NID-889: homepage site themes view adjustments

---

composer.json
composer.lock

Updated composer.json and composer.lock

Patch linkit to enable on link fields

---

config/sync/search_api.index.contacts.yml
config/sync/search_api.index.default_content.yml
config/sync/views.view.driving_instructors.yml

Full pager fixes broken total result count, desc field from taxonomy term entity allows searching by keyword such as Belfast, rather than BT1 alone

Swap to full pager, add taxo desc field

---

config/sync/views.view.articles_by_term.yml

Remove external links from teaser list

D8NID-1052

---

config/sync/core.entity_form_display.taxonomy_term.site_themes.default.yml
config/sync/core.entity_view_display.taxonomy_term.site_themes.default.yml
config/sync/field.field.taxonomy_term.site_themes.field_banner_image.yml
config/sync/field.storage.taxonomy_term.field_banner_image.yml

Related PR: https://github.com/dof-dss/nicsdru_origins_modules/pull/125

Replace thin banner image field with media reference type

---

config/sync/core.entity_form_display.node.embargoed_publication.default.yml
config/sync/core.entity_view_display.node.embargoed_publication.full.yml
config/sync/core.entity_view_display.node.embargoed_publication.search_result.yml
config/sync/field.field.node.embargoed_publication.body.yml
config/sync/field.field.node.embargoed_publication.field_published_date.yml
config/sync/field.field.node.embargoed_publication.field_secure_attachment.yml
config/sync/views.view.publications.yml

Configure embargoed publication display modes (same as publication display modes really) and add embargoed publications to publications search view.

Embargoed publications display config

---

config/sync/user.role.authenticated.yml
config/sync/user.role.author_user.yml
config/sync/user.role.health_condition_author_user.yml
config/sync/user.role.health_condition_supervisor_user.yml
config/sync/user.role.supervisor_user.yml

To all authenticated user roles

Extend view content references permission

---

config/sync/flag.flag.hide_content.yml

Ensures they can be toggled to hide in certain listings, eg: content by theme.

Allow the hide_content flag to appear on webform nodes

---

composer.json
composer.lock

Apply patch to scheduled transitions to make revisions in any language available for scheduling

D8NID-1074

---

config/sync/views.view.media_library.yml

Preprocessed in origins_media.module to make it prettier
After adding the extra column, looks like:

Add file mime relationship and field to media list display

---

config/sync/core.entity_view_display.node.driving_instructor.full.yml
config/sync/core.entity_view_display.node.driving_instructor.teaser.yml

Add missing classes to driving instructor category list in teaser view mode. (Forgot to add in earlier PR).
Tweak full content display for better preview when editing an instructor.

Driving instructor display fixes/tweaks

---

.platform.app.yaml
.platform/services.yaml
composer.json
composer.lock
install-redis.sh
web/sites/default/settings.platformsh.php

Moves us closer towards a smoother Drupal 9 adoption too by:
* PHP 7.4 for longer coverage of security releases and improved performance
* Adds composer 2 for faster builds
* Adds Redis 6 with latest PhpRedis (5.3.3)
* Optional verbose error output on platform.sh environments
* Latest platform.sh config (compatible with Drupal 9)
PhpRedis tags can be seen at https://github.com/phpredis/phpredis/tags

D8NID-1102 upgrade to PHP 7.4

---

composer.json
composer.lock

Fixes an issue with saving unpublished versions of published landing pages.  See https://www.drupal.org/project/drupal/issues/2918537#comment-13202872

D8NID-1120: Install patch for https://www.drupal.org/project/drupal/issues/2918537

---

.circleci/config.yml

Add extra step to rebuild Solr tracking info

D8NID-1131

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/honeypot.settings.yml
config/sync/tour.tour.honeypot.yml
config/sync/ultimate_cron.job.honeypot_cron.yml

Install honeypot module
(Relates to https://github.com/dof-dss/nidirect-site-modules/pull/355)

D8 nid 1104

---

composer.json
composer.lock

Apply a redirect module patch to add 'URL redirects' tab to taxonomy term edit form

D8NID-1141

---

composer.json
composer.lock

Addresses a core issue with layout builder, paragraphs and pending content revisions

Patch core to fix issue #3047022

---

config/sync/block_content.type.banner_deep.yml
config/sync/block_content.type.card_contact.yml
config/sync/core.entity_form_display.block_content.banner_deep.default.yml
config/sync/core.entity_form_display.block_content.card_contact.default.yml
config/sync/core.entity_view_display.block_content.banner_deep.default.yml
config/sync/core.entity_view_display.block_content.card_contact.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.full.yml
config/sync/field.field.block_content.banner_deep.field_teaser.yml
config/sync/field.field.block_content.card_contact.body.yml
config/sync/field.field.block_content.card_contact.field_card_style.yml
config/sync/field.field.block_content.card_contact.field_telephone.yml
config/sync/field.storage.block_content.field_card_style.yml
config/sync/field.storage.block_content.field_telephone.yml
config/sync/language.content_settings.block_content.card_contact.yml
config/sync/language.content_settings.taxonomy_term.landing_pages_contact_card_colou.yml
config/sync/taxonomy.vocabulary.landing_pages_contact_card_colou.yml

- new contact card block type
- add strapline (field_teaser) to banner deep block
- re-config allowed blocks to remove a few new types that crept in

Landing pages config:

---

config/sync/field.field.node.contact.field_location.yml
config/sync/field.field.node.gp_practice.field_location.yml
config/sync/geolocation_google_maps.settings.yml

Config exported to match up with geocoder v3 settings

Set geocoder region to gb, adjust field_location config

---

config/sync/core.entity_form_display.paragraph.card_plain.default.yml
config/sync/field.storage.paragraph.field_teaser.yml

... plus reorder form field display

Increase paragraph type plain card teaser character limit to 255

---

config/sync/webform.webform.universal_credit_payments.yml

Config for the D8 version of https://www.nidirect.gov.uk/forms/find-out-who-contact-about-money-taken-your-universal-credit-payment

Webform uc money off contact

---

composer.json
composer.lock

Also peg inline_entity_form to rc8 (for now) to allow its patch to apply cleanly

Patch paragraphs to allow editors to edit layout builder paragraph revisions

---

composer.lock

Protects against https://www.drupal.org/sa-core-2021-002

Update Drupal core to 8.9.14

---

config/sync/views.view.contacts_a_z.yml

Split query group into two: one for node title, one for supplementary title.
Dovetails with query alter and view preprocess code in nidirect_contacts.module
Relates to https://github.com/dof-dss/nidirect-site-modules/pull/375

Adjust contacts view filters

---

config/sync/views.view.workflow_moderation.yml

Relates to https://github.com/dof-dss/nicsdru_origins_modules/pull/156

Add missing label to table in content moderation views display

---

composer.json
composer.lock
config/sync/core.extension.yml

Permits entity update tasks to be run (recommend removal of module when complete)

Add and enable devel_entity_updates

---

composer.json
composer.lock

Relates to https://github.com/dof-dss/nicsdru_origins_modules/pull/160

Add video resource data to preprocess array from media core

---

composer.json
composer.lock
config/sync/core.entity_form_display.node.contact.default.yml

* For contacts addresses
* GP practices restricted to UK only so not needed on that entity type.

Add patch and config for preferred countries

---

composer.json
composer.lock
config/sync/core.extension.yml

Aids in tidying up taxonomy term migration.
Relates to https://github.com/dof-dss/nidirect-d8-mig-mods/pull/100

Add and enable migrate_process_trim module

---

composer.json
composer.lock

Remove patch for off-canvas style resets. 
Committed to core in https://www.drupal.org/project/drupal/issues/2958588#comment-14066125

Update core to 8.9.16

---

config/sync/csp.settings.yml

Content Security Policy - disable 'enforced'

D8NID-1238

---

config/sync/views.view.news.yml

* Omitted flag values as there was no query filtering on them, only extra joins.
* Preprocess code added to theme to overcome some shortcomings from Core.
Relates to https://github.com/dof-dss/nicsdru_nidirect_theme/pull/300

D8NID-1288 news RSS feed

---

config/sync/block.block.featuredcontent.yml
config/sync/block.block.featuredcontent_covid19.yml
web/sites/default/settings.php

Replace with block config now migrations have concluded

Remove FCL node references from env vars

---

config/sync/webform.webform.find_out_who_to_contact_about_mo.yml
config/sync/webform.webform.universal_credit_payments.yml

Config for https://dss.nics.gov.uk/forms/find-out-who-contact-about-money-taken-your-universal-credit-payment

Money taken off universal credit form

---

config/sync/webform.webform.contact_the_make_the_call_team.yml
config/sync/webform.webform.debt_management_enquiry.yml
config/sync/webform.webform.landlord_direct_payments.yml
config/sync/webform.webform.mother_and_baby_and_magdalene_la.yml
config/sync/webform.webform.proni_submit_an_enquiry.yml
config/sync/webform.webform.ready_for_universal_credit.yml
config/sync/webform.webform.report_legal_aid_fraud.yml
config/sync/webform.webform.should_i_get_tested_for_coronavi.yml
config/sync/webform.webform.site_feedback.yml
config/sync/webform.webform.state_pension_online_feedback.yml
config/sync/webform.webform.taxi_driver_theory_practice_1.yml
config/sync/webform.webform.taxi_driver_theory_practice_2.yml
config/sync/webform.webform.taxi_driver_theory_practice_3.yml
config/sync/webform.webform.taxi_driver_theory_practice_4.yml
config/sync/webform.webform.universal_credit_payments.yml
config/sync/webform.webform.year_10_subject_choices_quiz.yml
config/sync/webform.webform.your_comments.yml

Changes to webform configs exported from production.
Changes mainly around email handlers, (again) adding missing images, tweaks to confirmation messages, back to form buttons (enable on some, disable on others), enable email handlers for feedback form, remove my email address from one email handler(!), plus other tweaks

Webform production export fixes

---

config/sync/webform.webform.ready_for_universal_credit.yml
config/sync/webform.webform.year_10_subject_choices_quiz.yml

- Warning messages instead of error messages on getting ready for UC form.
- Correct right answer text for question 2 in year 10 subject choices quiz

More webform quick fixes

---

config/sync/webform.webform.contact_the_make_the_call_team.yml
config/sync/webform.webform.debt_management_enquiry.yml
config/sync/webform.webform.landlord_direct_payments.yml
config/sync/webform.webform.mother_and_baby_and_magdalene_la.yml
config/sync/webform.webform.proni_submit_an_enquiry.yml
config/sync/webform.webform.report_legal_aid_fraud.yml
config/sync/webform.webform.site_feedback.yml
config/sync/webform.webform.state_pension_online_feedback.yml
config/sync/webform.webform.your_comments.yml

Adds honey pot textarea to webforms submitting to email.  Also fixes proni enquiry webform to remove character counters on name fields and fix proni email handler to send to correct address.

For pooh bear

---

config/sync/core.extension.yml
config/sync/dblog.settings.yml
config/sync/ultimate_cron.job.dblog_cron.yml

Install nidirect_dblog module and override dblog_cron so that certain log entries are not deleted.
See associated PR https://github.com/dof-dss/nidirect-site-modules/pull/422

D8 nid 1363

---

.circleci/config.yml

Annotations in comments for better clarity! Bit of a YML-grenade, otherwise.
NB: once merged, an overnight test will be needed to confirm the workflows execute as they should. Any GH branch protection rules might also need a tweak in case job names have changed a little.

CI refinements and refactoring

---

config/sync/csp.settings.yml
web/sites/default/settings.php

Subdomain value is passed in as an env var

Update csp.settings.yml and settings.php

---

composer.lock

This fixes a faulty composer.lock file.

Force composer.lock file to update by deleting it and recreating it.

---

.platform.app.yaml

Last time didn't go too well ... messed up the composer.lock file when trying to resolve a conflict.
I have recreated the lock file by deleting it and recreating it (just running composer update --lock was not having the desired effect). Fingers crossed this resolves things ...

Push dev to edge again

---

composer.json
composer.lock

Apply latest patch to scheduled transitions contrib module

D8NID-1440

---

composer.lock

Expecting a core update too before this is merged into staging for final review.

Hotfix: Redirects handling on landing pages

---

.circleci/config.yml

Ensure that edge config still runs after sync failure

D8NID-1453

---

config/sync/field.field.node.publication.field_summary.yml

Text taken from legacy D7 site

Add description text to publication summary field

---

config/sync/field.field.node.embargoed_publication.field_summary.yml
config/sync/field.field.node.publication.field_summary.yml

and tweaks to help text for summary field in publications and embargoed publications.

D8NID-1466 extras: make summary field required in embargoed publications too

---

.circleci/config.yml
composer.json
composer.lock

See https://www.drupal.org/project/coder/issues/3010032#comment-14391143

Add missing slevomat coding standards dependency needed by drupal/coder

---

config/sync/views.view.popular_content.yml

- added missing book depth empty filter criteria
- removed list classes

D8NID-1472 Fix most popular conditions view

---

config/sync/origins_shamrock.admin.settings.yml

OPSH administration settings config

---

composer.json
composer.lock
config/sync/eu_cookie_compliance.settings.yml

See also related PR for styling - https://github.com/dof-dss/nicsdru_nidirect_theme/pull/349

D8NID-1408: EU Cookie Compliance - enable withdrawal of consent

---

composer.json
composer.lock

Patch fixes https://www.drupal.org/project/eu_cookie_compliance/issues/3305719

Add patch for EU Cookie Compliance module

---

.circleci/config.yml
composer.json
composer.lock

Looks like @neilblair's patch has made it into the latest release.

Fix patch application on clientside_validation, EU cookie compliance release

---

config/sync/core.extension.yml
config/sync/views.view.services_feed_services_catalogue.yml

- enable nidirect_services module (https://github.com/dof-dss/nidirect-site-modules/pull/480)
- changes to services catalog view that generates services-catalogue.json to enable custom serializer that converts relative urls in field content to absolute urls

D8NID-1540

---

composer.lock

(hotfix for OPSH json fastly caching)

Update to latest nicsdru_origins_modules 

---

config/sync/origins_shamrock.settings.yml

Prevent deployments switching banner off

opsh banner settings fix

---

config/sync/config_ignore.settings.yml
config/sync/origins_shamrock.admin.settings.yml
config/sync/origins_shamrock.settings.yml

Unpublish and disable display of OPSH banner and ignore the config for it.  We don't want future deployments re-enabling the banner.

D8NID-1547

---

composer.json
composer.lock

Resolves issue https://www.drupal.org/project/redirect/issues/3315928

Patch for redirect module

---

composer.json
composer.lock
config/sync/search_api_autocomplete.search.contacts.yml
config/sync/search_api_autocomplete.search.health_conditions.yml
config/sync/search_api_autocomplete.search.search.yml

To fix https://www.drupal.org/project/autoban/issues/3328787

Update autoban module

---

composer.lock

Change details https://git.drupalcode.org/project/whatlinkshere/-/commit/88c7b9c71c0317ea47f40712dd6d0e834f4b71bc

Version bump for whatlinkshere module

---

config/sync/webform.webform.appeal_a_firearms_decision.yml
web/modules/custom/nidirect_webforms/config/install/webform.webform.appeal_a_firearms_decision.yml

Add submission email handler to send submission to back office

Updated config for appeal firearms decision webform

---

composer.json
composer.lock

Composer needed to specify the exact version as otherwise would always upgrade to 10.2 which ideally needs to follow at a later point.
Contrib updates held for now, but should be updated separately.

Update core to 10.1.8 to fix SA-CORE-2024-001

---

web/modules/custom/nidirect_contacts/src/Plugin/Field/FieldFormatter/NIDirectTelephoneLinkFormatter.php
web/themes/custom/nicsdru_nidirect_theme/inc/preprocess.inc

Change extension prefix from 'x' to 'ext'.

D8NID-1658 fix display of phone numbers with extensions

---

composer.lock

Needed to avoid a 'field_workflow' missing error on drush commands with 10.3.0

Incorporate bugfix release for origins modules

---

config/sync/easy_google_analytics_counter.admin.yml
config/sync/views.view.popular_content.yml

- Change view id to GA4 property id
- Change sorting dimension from ga:pageviews to screenPageViews
- Do not show health conditions or contacts in home page most popular view block

Easy Google Analytics Counter adjusted configuration for GA4

---

composer.lock

Latest release fixes issue with translations menu opening unexpectedly

Update nicsdru_origins_modules to latest release

---

.circleci/config.yml

Tidied up some other minor issues in the CI conf file as well

Scheduled CI task to keep alive defined development environments

---

web/modules/custom/nidirect_webforms/js/prisonbooking.js
web/modules/custom/nidirect_webforms/src/Plugin/WebformHandler/PrisonVisitBookingHandler.php

Update prisonbooking.js
- Reset timeslots when settings.prisonVisitBooking.resetTimeslots === true
- Some other bugfixes and refactoring
Update PrisonVisitBookingHandler.php
Set a flag for JS to reset timeslot preferences and also have to clear form state and element default values / data serverside as well.

Update prison booking webform

---

config/sync/origins_translations.languages.yml

Updated config for origins translations

Merge dev to uat

---

composer.json
composer.lock
web/modules/custom/nidirect_contacts/src/Plugin/Field/FieldFormatter/NIDirectTelephoneLinkFormatter.php

Some slight differences between the way NIDirect's version of telephone_plus' formatter handles extensions. Extending it a bit to check for the unwanted extra phone extensions text seems to help

Update telephone_plus module and tweak site specific tel formatter

---

config/sync/webform.webform.taxi_driver_theory_practice_1.yml
config/sync/webform.webform.taxi_driver_theory_practice_2.yml
config/sync/webform.webform.taxi_driver_theory_practice_3.yml
config/sync/webform.webform.taxi_driver_theory_practice_4.yml
web/modules/custom/nidirect_webforms/config/install/webform.webform.taxi_driver_theory_practice_1.yml
web/modules/custom/nidirect_webforms/config/install/webform.webform.taxi_driver_theory_practice_2.yml
web/modules/custom/nidirect_webforms/config/install/webform.webform.taxi_driver_theory_practice_3.yml
web/modules/custom/nidirect_webforms/config/install/webform.webform.taxi_driver_theory_practice_4.yml

Various editorial changes from CET

Updated taxi theory practice test webform config

---

config/sync/core.entity_form_display.node.contact.default.yml
config/sync/csp.settings.yml

- disable address field integration as it appears to be broken and prevents map displaying with marker when editing a contact
- change CSP settings to stop warnings relating to maps.googleapis.com

D8NID-1671 Geolocation map fix

---

composer.lock
config/sync/core.entity_view_display.node.driving_instructor.teaser.yml

...to remove polyfill.io issue.

D8NID-1697 ~ Update Webform release

---

config/sync/views.view.search.yml
web/themes/custom/nicsdru_nidirect_theme/templates/misc/page--403.html.twig
web/themes/custom/nicsdru_nidirect_theme/templates/misc/page--404.html.twig

Some fixes to search, 404 and 403 pages which contain a broken link to a sitemap page.

D8NID-1702

---

web/modules/custom/nidirect_webforms/src/Plugin/WebformHandler/PrisonVisitBookingHandler.php

Fixed bug relating to when user chooses to change a timeslot and picks new ones and then changes mind and wants to go back to the original booked timeslot.

Pv amend scratch

---

config/sync/webform.webform.prison_visit_online_booking.yml
web/modules/custom/nidirect_webforms/config/install/webform.webform.prison_visit_online_booking.yml
web/modules/custom/nidirect_webforms/js/prisonbooking.jquery-validate-methods.js
web/modules/custom/nidirect_webforms/js/prisonbooking.js
web/modules/custom/nidirect_webforms/src/Plugin/WebformHandler/PrisonVisitBookingHandler.php

Bugfixes for
- Visitor badge text is "child" even when DOB not set
- Duplication of Visitor 1 ID is possible
- When you preview and hit previous, the time slots are no longer selected.
- Amend booking page: booking details showing actual form values and so change when booking is amended. Should always show original booking details.
Also reduced special requirements character limit to 400.

Pv amend add visitors

---

web/modules/custom/nidirect_webforms/src/Plugin/WebformHandler/NIDirectQuizResultsHandler.php

Fix "TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, Drupal\Core\Link given"

Fix php error "TypeError: htmlspecialchars()"

---

config/sync/webform.webform.prison_visit_online_booking.yml
web/modules/custom/nidirect_webforms/config/install/webform.webform.prison_visit_online_booking.yml

- Make additional_visitor_number required and default to 0.
- Add 'timeslot' class to all checkboxes for timeslots

Updated config

---

config/sync/webform.webform.prison_visit_online_booking.yml
web/modules/custom/nidirect_webforms/config/install/webform.webform.prison_visit_online_booking.yml
web/modules/custom/nidirect_webforms/src/Plugin/WebformHandler/PrisonVisitBookingHandler.php

And adjustment to info notice on main visitor details page.

Change "your details" to "main visitor details"
