dof-dss/nidirect-drupal

- composer.json
- composer.lock
Oddly, search_api installation with composer doesn't list drupal/facets as a dependency. While functional, if you ask PHPUnit to list groups the former fails on missing Traits provided by the latter making testing impossible. Adding the module as a dependency in composer fixes this.
Ditto for metatag and schema_metatag modules.
drupal-check and phpunit-finder added to require-dev as they're useful when you want to avoid global installs on CI services and a bit more intel about the test suites to help to split them up across multiple containers.
> Add contrib module dependencies and things to make phpunit usage easier

- config/sync/core.extension.yml
- config/sync/origins_workflow.auditsettings.yml
NB: assumes that https://github.com/dof-dss/nicsdru_origins_modules/pull/3 has either been merged into `development` or (as in my case) is checked out on a temporary evaluation branch.
I believe this will compliment https://github.com/dof-dss/nidirect-drupal/pull/28 which is involved with renaming nidirect_workflow to nicsdru_workflow.
> Enabe origins_workflow and layout modules; rename config to support

- README.md
Not possible to parse/embed Mermaid markdown directly via GitHub, but it is possible to use their rendering API endpoint to pass the base64 encoded contents and have it return a response as `image/jpeg` which, although fuzzy, is sufficient to use.
> Add mermaid diagram via API workaround

- config/sync/block.block.sitesearchblock.yml
- config/sync/search_api_autocomplete.search.search.yml
- config/sync/views.view.search.yml
There's a corresponding PR in the site-modules repo that provides a block for the views embed display to sit inside. Using views block display means you can't get the form to submit to a different page as the AJAX behaviour reloads the same page on submit.
> Add config for search autocomplete and block

- config/sync/config_split.config_split.local.yml
Because it generally obstructs the view of anything you want to look at
in the admin theme. Should default to being something you can switch on
as/when needed.
> Remove search_api_solr_devel from local split

- config/sync/core.base_field_override.node.health_condition_alternative.promote.yml
- config/sync/core.base_field_override.node.health_condition_alternative.status.yml
- config/sync/core.entity_form_display.node.health_condition.default.yml
- config/sync/core.entity_form_display.node.health_condition_alternative.default.yml
- config/sync/core.entity_view_display.node.health_condition.default.yml
- config/sync/core.entity_view_display.node.health_condition_alternative.default.yml
- config/sync/core.entity_view_display.node.health_condition_alternative.search_result.yml
- config/sync/core.entity_view_display.node.health_condition_alternative.teaser.yml
- config/sync/field.field.node.health_condition.field_alternative_condition.yml
- config/sync/field.field.node.health_condition_alternative.field_parent_condition.yml
- config/sync/field.storage.node.field_alternative_condition.yml
- config/sync/language.content_settings.node.health_condition_alternative.yml
- config/sync/node.type.health_condition_alternative.yml
- config/sync/views.view.health_conditions_a_to_z.yml
Content type, fields, display modes and views tweak.
This PR removes the extensive views preprocessing and instead uses a shallow node type to track/define the relationships between them and the original health condition.
> D8NID-197 Config for health condition alternative node type

- config/sync/views.view.content.yml
The Github diff hasn't done a very good job on this !
Changes relate to the admin 'Content' view.
The goal is to display 'moderation state' and allow appropriate filtering on this state for content which is moderated.
In addition to this, display published/unpublished status and allow filtering for content which is not moderated.
Note that the 'Status' column is used in both cases, and the 'Status' filter is also used in both cases. 
This has been achieved by adding both 'Status' and 'Moderation State' filters to the content page, but the 'Status' filter is hidden. The value of this hidden filter is set in code depending on the value of the 'moderation state' filter.
See related PR https://github.com/dof-dss/nicsdru_origins_modules/pull/35  for the code changes, this PR only contains the …
> Changes to content view for status filtering

- config/sync/views.view.content.yml
this column had been accidentally removed from the admin/content view during my recent changes
> reinstate useful 'operations' column 

- config/sync/views.view.articles_by_term.yml
Add view display to list 'campaigns' (landing pages) along with their theme/subtheme
Associated PRs:
https://github.com/dof-dss/nidirect-site-modules/pull/52 - cache invalidation for campaigns
https://github.com/dof-dss/nicsdru_nidirect_theme/pull/20 - allow for campaigns overriding taxonomy terms on listing pages
> Campaign aliases

- config/sync/block.block.footer.yml
- config/sync/nicsdru_origins_theme.settings.yml
NB: To avoid any confusion on first import... the footer menu will likely be empty on initial config import as menu links are considered content and aren't carried with the config export. Once the values are filled in by an admin, or we've faked them in code (if needed) things ought to look clearer :)
> Block config for footer menu and origins theme settings values

- config/sync/filter.format.basic_html.yml
- config/sync/filter.format.full_html.yml
- Whitelist from CS site's settings; respects entity embed and responsive images.
- Sets whitelist first; never trust user input to be safe.
- Remove tidying/hand-holding filters for full html; users will know what they're doing if they have perms to use this.
> D8NID-384 Set safe handling of basic html + full html text formats

- config/sync/user.role.admin_user.yml
- config/sync/user.role.anonymous.yml
- config/sync/user.role.apps_user.yml
- config/sync/user.role.authenticated.yml
- config/sync/user.role.author_user.yml
- config/sync/user.role.driving_instructor_supervisor_user.yml
- config/sync/user.role.gp_author_user.yml
- config/sync/user.role.gp_supervisor_user.yml
- config/sync/user.role.health_condition_author_user.yml
- config/sync/user.role.health_condition_supervisor_user.yml
- config/sync/user.role.news_supervisor.yml
- config/sync/user.role.supervisor_user.yml
https://www.drupal.org/sa-contrib-2019-093 introduced a new permission, this commit keeps our config in step with its impact
> Revoke blanket view terms permission for all but editor/admin roles

- config/sync/views.view.related_content.yml
Replace the dreaded the 'node_list' cache tag that was being produced by both block displays in the 'Related Content' view - replaced with the more specific custom cache tag 'taxonomy_term_list:<tid>'
> use custom cache tags

- config/sync/views.view.contacts.yml
Prior to this, the view wasn't correctly interrogating Solr for content resulting in zero results
> Reinstate fulltext search on contacts search API view

- config/sync/views.view.articles_by_term.yml
Amend the view that generates a list of campaigns (landing pages) as it does not need to exclude those with the 'hidden' flag
> remove flag check from campaign list

- config/sync/filter.format.basic_html.yml
- Address element to allow for existing content using this.
- translate attribute on paragraph tag as this is used by accessibility
tools to localise text; as found on the address field widget plugin
too.
> D8NID 445 Extend basic_html filter allowed html list.

- config/sync/views.view.gp_practices.yml
- config/sync/views.view.gp_practices_proximity.yml
Tokenised option in views config doesn't handler plurals, so we use a fixed empty header space and a preprocess hook in nidirect_gp.module to handle this for us. This PR is the views config
> D8NID-462 gp search results count

- config/sync/block.block.inthissection.yml
Reinstate block on contacts page (was working before but must have been lost when config was subsequently committed)
> D8NID-500 Reinstate 'in this section' block

- .platform.app.yaml
- .platform/services.yaml
- web/sites/default/settings.php
- Uses a regex to make sure the QA environment indicator is always set to a specific colour/title.
- Uses prod services config for caching/headers etc for a better likeness of the live environment.
- Drops the unwanted d7db service and memcache extension.
> Fix prod services, remove unwanted db service and tweak QA env

- .platform.app.yaml
- web/sites/default/settings.php
Some provisional presets of colour/title:
- Prod: NIDirect blue, Live.
- QA: Orange, 'QA', only enables if 'D8NID-qa' (case insensitive) is found in the branch name.
- Lando/local: Green, 'Local'. Added by Lando as a settings.local.php override.
- Anything else: Black, branch name.
> Fixes some environment indicator colours/titles

- composer.json
- composer.lock
See https://www.drupal.org/project/search_api_solr/issues/3085196 and https://www.drupal.org/project/drupal/issues/2876675
TL;DR: Solarium has been left on an older version for ages and search_api_solr is now following the upgrade path due to problems
leaving it at the current version. This causes a few ripples with core's event-dispatcher library, needing a small workaround until
Drupal 9 or 8.9/10 is released.﻿
> Update Solarium to 5.1.x for search_api_solr

- .platform.app.yaml
- composer.lock
- config/sync/block.block.inthissection.yml
- web/sites/default/settings.php
Config_readonly is a great module, it stops admins making changes to Drupal configuration through the UI that will be overwritten on the next deployment; a very frustrating situation for all.
However, setting the value to be active via an environment variable means when platform.sh deploys it can't apply database or config updates and leaves it in a rather half-baked state.
These changes will:
1. Default config_readonly to ACTIVE if there is no preference set already.
2. Disable it in the event the PHP_SAPI_CLIENT is present; ie platform.sh or drush.
I've also sneaked in some environment indicator colours for prod env, because I had it open in front of me :)
> Safely handle config_readonly mode on platform.sh

- config/sync/views.view.search.yml
Without this, default tag based caching means rows result stale render content after a Solr document is updated in the index.
Setting to search API tags keeps things in sync.
> Use search api tags to ensure search row render items are correctly expired when indexes are updated

- composer.json
- composer.lock
Mostly looking for instances of:
- memcache
- entityqueue
- solr devel
After seeing on-and-off references to them over the last few weeks. I think it's solely this memcache reference in composer that's left so this PR removes it.
If anyone has an older DB build with any memcache references they can source a new db from platform.sh
> Remove memcache module from the project; using Redis now

- composer.lock
- config/sync/core.entity_form_display.node.contact.default.yml
- config/sync/field.field.node.contact.field_location.yml
- Sets the geolocation widget to the current user's location for new locations, if the browser permits it.
- Moves the address field above the geolocation field on contact nodes.
- Sets up automatic, full-duplex geocoding/sync between address and geolocation fields.
> D8NID-558 improved geolocation address fields

- config/sync/core.entity_view_display.media.image.banner_deep.yml
- config/sync/core.entity_view_display.media.image.banner_thin.yml
- config/sync/core.entity_view_display.media.image.card_large.yml
- config/sync/core.entity_view_display.media.image.card_small.yml
- config/sync/core.entity_view_display.media.image.feature_card.yml
- config/sync/core.entity_view_display.node.feature.teaser.yml
- config/sync/core.entity_view_display.node.health_condition.full.yml
- config/sync/core.entity_view_mode.media.banner_deep.yml
- config/sync/core.entity_view_mode.media.banner_thin.yml
- config/sync/core.entity_view_mode.media.card_large.yml
- config/sync/core.entity_view_mode.media.card_small.yml
- config/sync/core.entity_view_mode.media.feature_card.yml
Creates and configures new media entity view modes needed to apply responsive image styles to media entity reference image fields (have assumed here that images in landing pages could be media entity reference fields).
Also changed the photo field on feature teaser display (/admin/structure/types/manage/feature/display/teaser) to use the new feature card display mode.
And also configured the photo field in health conditions full display mode to use the existing embed display mode.
> D8 nid 607

- .platform/routes.yaml
- config/development/system.performance.yml
Turn off Platform.sh default 'router cache' as it does not support push-based clearing.
This was causing several problems e.g. changes to a published node would not show until the cache expired, which could be up to a day.
In the long term, we intend to implement Fastly, and it would be good to set up a test instance before we go in to production.
In the meantime, the only other option really available to us is to configure Varnish, but this would involve a fair bit of effort that would be effectively time wasted.
> D8 nid 485 nocache

- config/sync/core.entity_form_display.node.article.default.yml
- config/sync/field.field.node.article.field_summary.yml
- config/sync/field.field.node.article.field_teaser.yml
Opening another PR on this.  Realised that #placeholder could be used for help text instead of or in addition to #description.  Placeholders have a restricted length - but have the advantage of (hopefully) being more visible and likely to be read by the user compared with descriptions which are shown after the field.
> D8 nid 682 - help text for articles

- .platform.app.yaml
Holding the PR open: needs the git clone to use HTTPS instead of SSH for fewer unnecessary access control headaches.
> D8NID-674 ckeditor refinement: fix drag 'n' drop issue

- composer.lock
- config/sync/core.entity_form_display.node.contact.default.yml
- config/sync/core.entity_form_display.node.gp_practice.default.yml
Introduces a change so that the map defaults to scaling the display to any existing point, and only provide the option to use the current location. That way, if you click it - it will keep the address field in sync, the same as if you move the pointer on the map. But it won’t overwrite any existing data.
Also updates the geolocation module to the most recent, stable version to include the latest bug fixes.
> D8NID-688 address config

- config/sync/views.view.media_library.yml
- Prioritise accuracy of usage over render efficiency.
- Default to full pager across all displays for consistency and ease of paging.
> D8NID-672 drop caching from media listing

- .platform/solr_config/schema.xml
- .platform/solr_config/schema_extra_types.xml
- .platform/solr_config/solrconfig_extra.xml
- .platform/solr_config/stopwords_en.txt
Matches Lando configuration. Changes the way the spell field is built and stored in Solr, as well as how it's analysed/tokenized and fed back to the application.
> Refine spelling field parameters and field types

- config/sync/views.view.content.yml
Bring published/unpublished exposed filter on content admin screen into line with Drupal core i.e. make it a 'grouped' filter.
Also related to PR https://github.com/dof-dss/nicsdru_origins_modules/pull/72
> Use grouped publish filter

- .platform.app.yaml
- config/sync/system.date.yml
Tell Drupal to handle our timezone: includes all aspect of date handling; UI, cron plugins etc.
All logs, underlying database timestamps and other deeper system service timestamps are stored in UTC as standard. That's actually very helpful when analysing dates across ranges that cross over BST.
> D8NID-746 system time

- config/sync/linkit.linkit_profile.default.yml
Now provides site themes options for editors, like the one below:
> Include LinkIt matcher for site themes

- config/sync/core.entity_form_display.node.featured_content_list.default.yml
- config/sync/core.entity_view_display.node.featured_content_list.default.yml
- config/sync/core.entity_view_display.node.featured_content_list.full.yml
- config/sync/core.entity_view_display.node.featured_content_list.teaser.yml
- config/sync/field.field.node.featured_content_list.field_featured_content.yml
- config/sync/field.field.node.featured_content_list.field_subtheme.yml
- config/sync/field.field.node.featured_content_list.field_tags.yml
- config/sync/field.storage.node.field_tags.yml
- config/sync/views.view.news.yml
Adds:
- Two fields to the featured content list node type so that we can map them to existing site themes, or, some arbitrary tags for the pages that fall between the cracks such as homepage and news landing pages.
Relates to https://github.com/dof-dss/nidirect-site-modules/pull/187
> D8NID-764 news queue

- config/sync/core.extension.yml
- config/sync/user.role.editor_user.yml
NB: CI will fail until composer.lock is updated to reflect a new release in https://github.com/dof-dss/nicsdru_origins_modules which is where the module providing this functionality exists.
> D8NID-755 Enable origins metatag module + permission relating to it

- config/sync/workflows.workflow.nics_editorial_workflow.yml
Editors have permissions to use the "quick publish" transition allowing them to create a draft and publish it, skipping the "needs review" moderation state.
However, when editing a published revision, editors would be forced to save the revision as a draft or "needs review" - they were not able to save the new revision as published.
This PR allows editors to edit a published revision and save the new revision as published.
> Modifies quick publish workflow transition to allow published to published transition

- .circleci/config.yml
This PR does the following:
- Every night, Mon - Fri, it kicks off an 'edge build' that takes the development branch, swaps all dof-dss packages to use HEAD on `development` branches, then pushes the contents into a branch called  `D8NID-edge`. This is then carried over to platform.sh via the webhook integration in use at the moment where a build/deploy task is triggered. The environment is active and won't normally be pulled down until it's no longer needed, eg: site being live.
- Half an hour later, a second job runs a platform sync task on that environment to update the content from the master environment.
Circle CI doesn't push a throwaway branch to the platform.sh repo, because when I originally did this the github integration seemed to prune my branch some way through the build …
> D8NID-800 scheduled dev build

- config/sync/search_api_autocomplete.search.contacts.yml
Should be operating with the underlying search fulltext filter criteria but in this case something's not quite feeding through correctly. This config setting corrects this for the autocomplete search and gives matching autocomplete results + search results page content on the contacts search.
> D8NID-785 Specify fulltext title field for contacts autocomplete search

- .circleci/config.yml
Sets up Circle CI so it runs our functional tests after it has built the edge environment, every workday evening.
Once the timings settle, it might be an idea to incorporate into the main pipeline especially if it runs in parallel with the long unit/kernel tests job. There shouldn't be any delay introduced, but it would consume extra CI compute/build minutes.
> Headless testing of nightwatch tests against platform.sh environment

- .circleci/config.yml
Makes sense to run after latest code + content rather then just after
latest code.
> Shift functional tests after content refresh.

- .circleci/config.yml
Introduce the build step because it contains the checkout command + other files that we need for the functional tests
> Fix missing workflow dependencies

- config/sync/core.entity_view_display.node.health_condition.full.yml
- config/sync/core.entity_view_display.taxonomy_term.hc_info_sources.full.yml
Partial fix for https://digitaldevelopment.atlassian.net/browse/D8NID-630 where the information source for a health condition does not display correctly because the twig template expects there to be a full content display mode for the info source taxonomy term.
A separate ticket (and resulting PR) will handle the other part of this fix - see https://digitaldevelopment.atlassian.net/browse/D8NID-839
> D8 nid 630 hc info sources

- config/sync/core.entity_view_display.taxonomy_term.site_themes.full.yml
Ensure we can print any summary and description fields before the main info + services list.
See https://github.com/dof-dss/nicsdru_nidirect_theme/pull/147 for template.
> D8NID-847 theme page content array adjustments

- .circleci/config.yml
So without this, the first stage of building the edge build works okay... it checks out the dev package and commits them back to the right branch. However, when the sync_data command runs it's using a build artefact from the development branch which explains why the functional tests kept not working... because they were running off tagged releases a week behind.
This step should add the extra step to check out the edge branch (already built by the earlier job) before running nightwatch tests.
> Check out the edge branch for nightly functional testing

- .circleci/config.yml
Ensures when we persist the workspace that it carries forward composer
packages that are dev-development, not tagged releases, which the
standard build task would do.
> D8NID-849 Make nightly sync and test workflow use a different build command.

- config/sync/views.view.site_themes.yml
Taxonomy navigator module uses the weight property, rather than a discrete field value.
> D8NID-844 Order homepage site themes based on taxonomy weight

- .circleci/config.yml
Shouldn't really be needed but this ensures the index is completely
empty to avoid issues of double-counting seen several times even after
syncing from master environment.
> Forces a full purge of environment solr contents before reindexing.

- config/sync/core.extension.yml
Enable the origins_unique_title module.
NB: tests will fail until the origins modules repo has a new point release, after which the module will be present allowing it to be enabled.
> D8NID-861 duplicate nodes

- .circleci/config.yml
The container image needed to be changed so we can drop in our custom PHP extensions/config. It also needed the platform CLI tool installing.
The missing link is the CLI token env var, added to the D8 application master environment that allows the NICS PSH user to access services between the D7 and D8 projects.
> Change to better container, add platform CLI tool, run against existing instances

- .circleci/config.yml
- composer.json
- composer.lock
It keeps us in line with the latest releases but it does report errors autoloading test classes for some reason. You can work around this with a `-e "*/tests/src/*"` which isn't great but it means we're still able to detect deprecated code in our non-test classes until this quirk is fixed by us or upstream
> Update drupal-check + phpstan libraries

- config/sync/user.role.anonymous.yml
- config/sync/user.role.authenticated.yml
Without this, anonymous users can't see symptoms in the health condition search results.
> Grant term view permission for health condition symptons to anon + auth users

- .platform.app.yaml
- composer.lock
- migrate-config-sync.sh
- migrate-full-import.sh
This PR aims to:
- Provide a script we can use to sync the db config from the migrate modules (excluded from the main config/sync folder due to past config import issues).
- Full rollback + re-import of content. Migrate import alone is not enough to 'top-up' the content as there are deletions to contend with. It's far safer (although time consuming) to roll it all back, re-import and re-add any extras we need on top of that.
> D8NID-900 migrate config sync and full import

- config/sync/search_api.index.health_conditions.yml
- config/sync/views.view.health_conditions.yml
- Change parse mode for the search terms to "multiple terms" rather than "phrase" in the view
- Enable partial word matching on many fields
- Alter boosts for fields similar to D7 version
- Remove html filter boosting
These changes should produce a fairly similar search results to the present D7 version.
> Health conditions search tuning:

- config/sync/views.view.contacts_a_z.yml
- config/sync/views.view.health_conditions_a_to_z.yml
- config/sync/views.view.news.yml
Had a look through all views to find those using the 'node_list' cache tag and replaced it with a 'handy cache tag' where possible (in order to greatly improve performance).
Views changed:
- Contacts A-Z
- Health conditions A-Z
- News views
> D8 nid 915

- config/sync/core.extension.yml
- config/sync/metatag.metatag_defaults.node__health_condition.yml
- config/sync/metatag.settings.yml
Allows Health Condition nodes to extend and define MedicalPage schema elements, augmented with preprocessing in nidirect_health_conditions.module
> Enable schema_metatag_web_page

- config/sync/views.view.related_content.yml
Flag module ids leave something to be desired... ambiguous++. 
Not all bad though, as the admin labels are very clear and anyone working with the views UI shouldn't struggle with that.
> Don't show content flagged as 'Hidden'

- composer.json
- composer.lock
Replaces the canonical path (node/123) with the aliased title for better UX. Underlying markup uses a content UUID to help avoid losing track of the link in case the alias changes, eg:
```
<a data-entity-substitution="canonical" data-entity-type="taxonomy_term" data-entity-uuid="bd9bb3f3-e3a3-42e1-ae2d-8de8f52b054e" href="/information-and-services/people-disabilities/motoring-and-transport">some link text</a>
```
and
```
<a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="5920e0e0-5654-4321-af07-2d126b1a19cc" href="/articles/fixed-penalties-motoring-offences">some link text</a>
```
> D8NID-870 LinkIt substitution plugin output

- config/sync/views.view.contact_children.yml
Enable editors to promote contacts to the top of contact_children views - e.g. on a contact page for gov departments, The Executive Office would be promoted to the top followed by the rest of departments in alphabetical order.
See also https://github.com/dof-dss/nidirect-site-modules/pull/280
> Sort contact_children view by 'sticky at top of lists' 

- composer.json
- composer.lock
Patch adds phone extension into link text of phone links.
https://www.drupal.org/project/telephone_plus/issues/3186246
https://www.drupal.org/files/issues/2020-12-03/3186246-1.patch
> Adds patch for telephone_plus 

- composer.json
- composer.lock
- config/sync/core.extension.yml
Used on the legacy site. The 8.x version of the [node_edit_protection](https://git.drupalcode.org/project/node_edit_protection) contrib module seems to be put together well enough to not warrant a purely custom code approach.
> D8NID-872 node edit protection

- config/sync/field.field.node.health_condition.field_alternative_condition.yml
- config/sync/field.field.node.health_condition.field_parent_condition.yml
Ensures that as HC nodes move between moderation states, the HCA nodes are kept in sync for all user roles without triggering deeper moderation or widget validation errors.
> Allow unpublished content to be referenced

- config/sync/field.storage.node.field_attachment.yml
D8NID-1040: allows publications to reference more than a single document media entity.
> Set cardinality on attachment field to be unlimited

- composer.json
- composer.lock
Avoids interrupting the tagging numbering. It should have been possible to re-tag and do the mess-around with tag numbers, but it's just as easy to reference a specific commit in the master branch as a temporary stopgap.
> Temporarily peg nicsdru_nidirect_theme to specific master commit

- composer.json
- composer.lock
Cut a specific release for 8.8.x versions as Core 8.9.x/9.x changes the namespace for the alias manager service which the link manager service depends on.
> Update whatlinkshere module to 1.6 to fix inefficient drupal console commands

- config/sync/block.block.healthconditionsfacetsummary.yml
- config/sync/block.block.mainpagecontent.yml
- config/sync/block.block.originssocialsharing.yml
- config/sync/block.block.views_block__site_themes_site_themes_home_page.yml
- move back into the content region (better DOM position for accessibility) and disable it (will be output via drupal_block() call in twig - see https://github.com/dof-dss/nicsdru_nidirect_theme/pull/224)
- enable block on GP practices
> Move social sharing block

- config/sync/ultimate_cron.job.google_analytics_counter_cron.yml
Ensures that the most popular blocks are routinely updated
> Enable the GAC cron task

- config/sync/responsive_image.styles.article_full.yml
- config/sync/responsive_image.styles.card_large.yml
- config/sync/responsive_image.styles.card_small.yml
- config/sync/responsive_image.styles.card_thumbnail.yml
- config/sync/responsive_image.styles.deep_banner.yml
- config/sync/responsive_image.styles.feature_card.yml
- config/sync/responsive_image.styles.inline.yml
- config/sync/responsive_image.styles.inline_expandable.yml
- config/sync/responsive_image.styles.inline_xl.yml
- config/sync/responsive_image.styles.inline_xl_expandable.yml
- config/sync/responsive_image.styles.landing_full.yml
- config/sync/responsive_image.styles.news_thumbnail.yml
- config/sync/responsive_image.styles.portrait_float.yml
- config/sync/responsive_image.styles.portrait_float_expandable.yml
- config/sync/responsive_image.styles.portrait_full_width.yml
- config/sync/responsive_image.styles.thin_banner.yml
Convert responsive image styles to use img srcset method for delivering various image sizes.  
The picture method we had been using was cumbersome and probably unnecessary since we just need to deliver the same image in various sizes (see https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/).  
Another reason is that Drupal / Twig was not outputting valid html for the picture element and its child source elements.  `<source>` elements are void elements (no closing tag) - but for some reason Drupal adds the closing tag even though its in the twig as `<source />`.  Rather than fight this weirdness I decided to make the leap to the srcset method instead.
Related: 
- https://github.com/dof-dss/nicsdru_nidirect_theme/pull/228
- …
> A11y fixes

- composer.lock
Updates the nidirect theme to the latest version.  I noticed a small gaff in yesterdays release affecting the images in all cards (like the features on the homepage).  The images have margins ruining the look of the card.  Not a huge deal - but annoying.
> Updates composer.lock with updated version of nidirect theme

- config/sync/core.entity_form_display.node.embargoed_publication.default.yml
- config/sync/core.entity_view_display.node.embargoed_publication.default.yml
- config/sync/core.entity_view_display.node.embargoed_publication.diff.yml
- config/sync/core.entity_view_display.node.embargoed_publication.full.yml
- config/sync/field.field.node.embargoed_publication.field_secure_attachment.yml
- config/sync/field.storage.node.field_secure_attachment.yml
Ensures we don't need to stick two file fields on Document entities; one for private one for public storage.
> Convert media reference field to private file field

- .platform.app.yaml
We're likely going to use GCP Scheduler to kick off the HTTP requests for cron as it can reliably execute every 60 seconds.
> Drop internal cron so we can use external service

- config/sync/core.entity_view_display.node.application.diff.yml
- config/sync/core.entity_view_display.node.application.full.yml
- config/sync/field.field.node.application.body.yml
- config/sync/field.field.node.application.field_additional_info.yml
Hide labels on body field (Before you start) and additional info field.  Modified help text to indicate authors should add their own headings into the content of these fields.
> D8NID-1096: application pages display / field changes

- .platform.app.yaml
Allows PHP 7.4 to make use of this opcache, which should give some performance improvements.
> Add APCu extension

- config/sync/core.entity_view_display.node.application.default.yml
- config/sync/core.entity_view_display.node.application.diff.yml
- config/sync/core.entity_view_display.node.application.full.yml
Restoring this config for application pages which erroneously got removed by commit 8ebcf4e9
> Hide body field and additional info field labels

- config/sync/views.view.content.yml
- config/sync/views.view.workflow_moderation.yml
Sorry, a YAML-bomb :)
Screenshots below to make it easier to see the changes!
**Main content listing**
**My Drafts**
**All drafts**
**Needs review**
**Needs audit**
> Updated exposed filters to be more consistent for content listings

- .circleci/config.yml
Something in the job as a whole must be clearing this value, so try to reset this using drush as an interim measure.
> Fix missing GAC token variable; value kept in env var

- web/sites/default/settings.php
- Set default of services.yml config
- Use env vars for simple environment indicator colours/text
- Only use production config split on production
> Remove duplicated or unnecessary config overrides

- config/sync/block.block.featuredcontent_covid19.yml
- config/sync/block.block.mainpagecontent.yml
- config/sync/block.block.pagetitle.yml
- config/sync/block.block.pagetitle_banner_top.yml
- config/sync/block.block.primaryadminactions.yml
- config/sync/block.block.tabs.yml
- web/sites/default/settings.php
NB: COVID-19 block node id liable to shift with migrations, so block config may need to be updated to reflect a shifting high water line for content ids after each migration run.
> D8NID-1127

- config/sync/block.block.featuredcontent.yml
- config/sync/block.block.featuredcontent_covid19.yml
- config/sync/block.block.featurednews.yml
- config/sync/block.block.healthconditionsatoz_sidebar_2.yml
- config/sync/block.block.healthconditionsfacetsummary.yml
- config/sync/block.block.healthconditionsrelatedconditions.yml
- config/sync/block.block.metofficeweather.yml
- config/sync/block.block.originssocialsharing.yml
- config/sync/block.block.pagetitle_banner_top.yml
- config/sync/block.block.primaryadminactions.yml
- config/sync/block.block.relatedcontentblock.yml
- config/sync/block.block.tabs.yml
- config/sync/block.block.translationhelplink.yml
- config/sync/block.block.views_block__popular_content_pop_by_term.yml
- config/sync/block.block.views_block__popular_content_pop_info_site_wide.yml
- config/sync/block.block.views_block__popular_content_pop_services_site_wide.yml
- config/sync/block.block.views_block__site_themes_site_themes_home_page.yml
Move the featured content block for covid-19 features into the top banner region.  There are changes to featured items node ids for the two featured content blocks - but I don't think this should break anything because these ids are set by env variables on edge.
> Block layout changes 

- composer.json
- composer.lock
- config/sync/field.field.node.application.field_subtheme.yml
- config/sync/field.field.node.article.field_subtheme.yml
- config/sync/field.field.node.embargoed_publication.field_subtheme.yml
- config/sync/field.field.node.external_link.field_subtheme.yml
- config/sync/field.field.node.featured_content_list.field_subtheme.yml
- config/sync/field.field.node.health_condition.field_subtheme.yml
- config/sync/field.field.node.landing_page.field_subtheme.yml
- config/sync/field.field.node.publication.field_subtheme.yml
- config/sync/field.field.node.webform.field_subtheme.yml
Fine for admins who have the bypass access checks permission. Not so for other roles, so this plugin helps as an interim solution until core sorts itself out and makes this configurable :)
> D8NID-1140 allow editors to reference unpublished taxonony term entities

- .circleci/config.yml
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/upgrade_status.settings.yml
CI steps might fail as I've twiddled the job names and that won't match up with broader repo config. I've done this to split the coding standards from deprecated code checks; these can run in parallel.
> Drop upgrade_status module usage; fall back to using phpstan/drupal-check in CI

- config/sync/devel.settings.yml
Undefined error handler means PHP errors are all rendered to output which isn't desirable
> Add devel config

- config/sync/block_content.type.information_notice.yml
- config/sync/core.entity_form_display.block_content.information_notice.default.yml
- config/sync/core.entity_view_display.block_content.information_notice.default.yml
- config/sync/core.entity_view_display.node.landing_page.full.yml
- config/sync/editor.editor.layout_builder_html.yml
- config/sync/field.field.block_content.information_notice.body.yml
- config/sync/language.content_settings.block_content.information_notice.yml
- config/sync/layout_builder_restrictions.plugins.yml
- Add information notice block for landing pages (to be used instead of ckeditor info-notice style on the text block)
- Re-enable layout builder block restrictions by region to ensure editors cannot, for example, add cards into the one column layout section or add information notice blocks into x2 and x3 card sections.
- Remove p.info-notice style from layout builder text format
> Landing pages block updates 2

- .platform.app.yaml
- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/csp.settings.yml
- config/sync/filelog.settings.yml
* Adds the content security policy module with report only config.
* Adds filelog module to avoid spraying a firehose of events at dblog (platform.sh can't support syslog)
* Cron handler to prune away compressed log files over 30 days old.
> D8NID-1189 CSP module and config

- composer.json
- composer.lock
Relates to https://www.drupal.org/project/filelog/issues/3133252, surfaces itself with a clash between core/fastly and filelog modules.
Nudging the logger factory priority ensures it's loaded before the file system service and avoids a circular dependency issue.
> Set logger factory priority to mediate between fastly and filelog module services

- composer.json
- composer.lock
Adding this module as it's been a PITA to debug twig now that Kint isn't a sub-module to Devel. I ran into the old issue that any {{ kint() }} inserted into a template would result in the site redirecting to install.php. Prior to the Devel update you could get around this by requiring the module in settings.php and then calling Kint::$maxLevels = 3; but this doesn't work anymore.
> D8NID-1205 ~ Adding Twig VarDumper to make it easier to debug templates

- config/local/syslog.settings.yml
- config/sync/core.extension.yml
- config/sync/csp.settings.yml
- config/sync/dblog.settings.yml
- config/sync/ultimate_cron.job.dblog_cron.yml
- config/sync/views.view.watchdog.yml
* Syslog can't be used across all environments
* Filelog clashes with fastly on production
* Reinstate dblog so we have a single consistent means of logging Drupal activity across all environments
> D8NID-1189  adjust logging options

- config/sync/webform.settings.yml
Filled in the gaps based on vanilla webform config. 
NB: recommend redirect id 39129 is deleted (`form/contact-the-make-the-call-team`) as otherwise saving/importing config can clash with a redirect that covers that path.
> Updated general webform config

- config/sync/csp.settings.yml
Handy query to extract these:
```
select REGEXP_SUBSTR(variables, '"referrer": .+') as referrer, REGEXP_SUBSTR(variables, '"violated-directive": .+') as violation, REGEXP_SUBSTR(variables, '"blocked-uri": .+') as blocked_uri from watchdog where type = 'csp' group byXP_SUBSTR(variables, '"referrer": .+')\G;
```
> Add refinements to policy based on logged entries so far

- config/sync/views.view.contacts.yml
Allows closer matches to D7 equivalent.
Related: https://github.com/dof-dss/nidirect-site-modules/pull/387
> Minor config to contacts solr search mode

- config/sync/core.entity_view_display.media.image.article_float.yml
- config/sync/core.entity_view_display.media.image.article_float_expandable.yml
- config/sync/core.entity_view_display.media.image.article_full_expandable.yml
- config/sync/core.entity_view_mode.media.article_float.yml
- config/sync/core.entity_view_mode.media.article_float_expandable.yml
- config/sync/core.entity_view_mode.media.article_full_expandable.yml
- config/sync/filter.format.basic_html.yml
- config/sync/filter.format.full_html.yml
- config/sync/image.style.nigov_float_x1.yml
- config/sync/image.style.nigov_float_x2.yml
- config/sync/responsive_image.styles.inline.yml
- config/sync/responsive_image.styles.inline_expandable.yml
- config/sync/responsive_image.styles.inline_xl.yml
- config/sync/responsive_image.styles.inline_xl_expandable.yml
… and adjustments to basic_html text format to enable them and disable others.
In D7, the image styles available in CKEditor constrained image width only.  In D8, the corresponding styles constrain both width and height - and these present problems migrating from D7 to D8.
The changes in this PR are needed to better align with images styles migrating from D7. The changes will mean images embedded in article content will only have fixed widths - image height will not be fixed or cropped.  And the list of available image view modes that editors will see in ckeditor is reduced to just 4:
Article float (resp img mapping: inline)
Article float expandable (resp img mapping: inline_expandable)
Article full (resp img mapping: inline_xl)
Article full expandable (resp img mapping: …
> New image styles and view modes

- config/sync/core.entity_form_display.node.embargoed_publication.default.yml
- config/sync/core.entity_form_display.node.publication.default.yml
- config/sync/core.entity_view_display.node.embargoed_publication.default.yml
- config/sync/core.entity_view_display.node.embargoed_publication.diff.yml
- config/sync/core.entity_view_display.node.embargoed_publication.full.yml
- config/sync/core.entity_view_display.node.embargoed_publication.search_result.yml
- config/sync/core.entity_view_display.node.embargoed_publication.teaser.yml
- config/sync/core.entity_view_display.node.publication.default.yml
- config/sync/core.entity_view_display.node.publication.diff.yml
- config/sync/core.entity_view_display.node.publication.full.yml
- config/sync/core.entity_view_display.node.publication.search_result.yml
- config/sync/core.entity_view_display.node.publication.teaser.yml
- config/sync/core.entity_view_display.taxonomy_term.site_themes.full.yml
- config/sync/field.field.node.embargoed_publication.field_additional_info.yml
- config/sync/field.field.node.publication.field_additional_info.yml
Add footer text (field_additional_info) to publications content types.
Set footer text in full display to use ancestral value format on both themes and publications.
> footer text (field_additional_info)

- config/sync/geocoder.geocoder_provider.googlemaps.yml
Allows geocoding of UK and IE addresses and postcodes. A blank region id yields 0 results and it's not possible to dynamically adjust the region config owing to the way the geocoding module and libraries interact with each other.
This handy adjustment allows google maps to look at a wider scope of region that includes both the UK and Ireland, but excludes some of the tricker/wackier matches you might get across in the US or wider afield in the world.
Details of region codes: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
> Set region id to eu

- config/sync/views.view.contacts.yml
- Query must contain all words entered
- Restrict fields to address, body and title, plus supplementary contact value.
- Use sloppy phrase with distance for optimal results; vague terms can appear but if far apart from other phrase terms they're scored lower. This helps places with a placename in the title rise above those that are located in the same area.
> Contact search filter refinements

- .platform/routes.yaml
Should help address the rare instances where Drupal can generate a base URL of /index.php/pathname.
> Catch-all routing redirect config

- config/sync/csp.settings.yml
A few extra things triggered by:
- Google translate service on articles.
- The site theme's manifest (in the `<head>` element), ie: `themes/custom/nicsdru_nidirect_theme/images/favicons/site.webmanifest`
> CSP refinements based on logged exceptions

- config/sync/webform.webform.site_feedback.yml
- config/sync/webform.webform.your_comments.yml
HTML tags now stripped in nidirect_webforms.module, allows the benefits to be re-used across storage + any attached handlers.
> Remove HTML regex from webform validation

- .gitignore
- config/sync/migrate_plus.migration.money_advice_service_rss_articles.yml
- config/sync/ultimate_cron.job.money_advice_articles.yml
* Adds an exception to gitignore to let us house the migration config for MAS content. Without that, we would need to reinstall the module each time we want to make changes to the active migration config (it's copied into active state from config/install on module installation).
* Turns on the cron task handler.
**NB: MAS module should be uninstalled before this config goes in. Otherwise it'll grumble about existing config being present.**
> D8NID-1227 enable MAS content import

- config/sync/views.view.popular_content.yml
Fixes styling issue with popular content menus by removal of nav-menu and nav-item classes.  Classes added back in for most popular content blocks - all except the popular conditions block on the illnesses and conditions page.
> Popular info menu fix

- config/sync/webform.webform.site_feedback.yml
- config/sync/webform.webform.your_comments.yml
- Add auto reply email to site feedback form (top nav one) in line with same on page feedback form
- Simple thank you auto reply - does not contain the info the user submitted.
- Auto reply conditional - only enable if user wants a reply and provided and email address
- Plain text format for emails sent to CET
- Exclude HTML form elements from the email sent to CET
> Feedback forms fixes:

- .platform.app.yaml
Suggest we leave removing migrate config and modules until a stable period after launch.
> Remove migrate config sync script from deploy steps

- config/sync/core.extension.yml
- config/sync/migrate_plus.migration.money_advice_service_rss_articles.yml
- config/sync/ultimate_cron.job.money_advice_articles.yml
Includes updated MAS article import config hashes.
NB: Ahead of deployment:
* Uninstall all migrate modules (purges config)
* Deploy code; config import will pull in the config from config/sync and make it active in the database.
Once in place: `drush ms` to test. If you get a migrate plugin error, the existing config hasn't been correctly purged before importing the new.
> D8NID-1356: Remove unwanted migrate modules to permit MAS articles to import

- config/sync/webform.webform.site_feedback.yml
- config/sync/webform.webform.your_comments.yml
Standardises the response format for anon + auth users as AJAX submission/response doesn't seem to work for anon users without the use of a CSRF token, which Drupal core does not add for anonymous users.
Markup removed from config: it was used to display the correct format in the inline response but it doubles up with the existing status area messages markup when using the messages confirmation option.
> Swap to message confirmation and remove embedded markup

- config/sync/webform.webform.contact_the_make_the_call_team.yml
- config/sync/webform.webform.debt_management_enquiry.yml
- config/sync/webform.webform.proni_submit_an_enquiry.yml
- config/sync/webform.webform.state_pension_online_feedback.yml
The pattern attribute on textareas is usually used to prevent submission of html - and browsers seem to support it ok - but it is not allowed in the html spec ...
> Remove regex pattern validation on textareas in various webforms

- config/sync/webform.webform.landlord_direct_payments.yml
Hotfix for https://www.nidirect.gov.uk/admin/structure/webform/manage/landlord_direct_payments/handlers - update email address the webform sends to.
> Update email address in email handler

- .platform.app.yaml
- config/development/system.performance.yml
- config/production/system.performance.yml
- config/sync/system.performance.yml
Adjust cache-control max-age to 5 mins instead of 1 year.  We don't want browsers or proxies to cache pages for that long.  Set Surrogate-Control header for Fastly and let Fastly cache a page for 24 hours.
> Page max age adjustment

- config/sync/core.extension.yml
- config/sync/http_cache_control.settings.yml
- config/sync/system.performance.yml
At present, all pages have a cache-control: max-age=315600 (1 year).  This means that browsers and proxies and Fastly can cache for 1 year.
In relation to Fastly, caching for 1 year is not a problem because cached pages are purged when necessary.
But for browsers and proxies, 1 year is too long and there is no mechanism to purge browser and proxy caches.
The http cache control module was already present - just not installed.  The module allows us to set separate headers for controlling browser, proxy and reverse proxies like Fastly.  In relation to Fastly, we can set the surrogate-control header which Fastly will use instead of cache-control if it is present.
- For browsers and proxies we want cache-control: max-age=300, public, stale-if-error=180, stale-while-revalidate=180
- For Fastly, …
> Enable http cache control module and set cache-control and surrogate-control values

- composer.json
- composer.lock
Update to nidirect_site_modules 1.0.7 - contains hotfix for major bug preventing reverting to previous revisions
> Updates nidirect_site_modules to 1.0.7 

- .circleci/config.yml
Add backup data sync in case the first sync fails in the overnight Edge build
> D8NID-1453

- config/sync/views.view.popular_content.yml
Updates popular content views so that:
- "information site wide" shows articles, contacts, health conditions, landing pages and news (application removed)
- "services site wide" shows application pages only (cold weather payment removed - the cold weather payment checker is an application page)
- "by top-level term" and "by term" show articles, health conditions and landing pages only
> Fix issue where home page "Popular information" is listing popular services

- composer.json
- composer.lock
Was originally using a twig template to manipulate iframe attributes and stop deprecated frameborder attributes being output - but it stopped working after D9 upgrade and caused video thumbnails to disappear in the media browser. 
Instead of using twig, found this patch that fixes the oembed field formatter and removes the deprecated iframe attributes.  https://www.drupal.org/project/drupal/issues/3071446
> Patch to remove invalid iframe attributes from oembed field formatter

- config/sync/webform.webform.report_legal_aid_fraud.yml
Fixes an issue with the Report Legal Aid Fraud webform where the generated email contains duplicate headings. Instead of using [webform_submission:values] token to output everything, we selectively output specific elements to avoid outputting wizard elements whose title is the same as a fieldset that wraps elements within.
> D8 nid 1464

- composer.json
- composer.lock
Must have been dropped as a dependency from another package in a recent update. Re-adding here, explicitly, as otherwise we can't use the utilities this package provides from our custom module.
> Add Nette\Utils package required for array handling in custom module

- config/sync/block.block.translationhelplink.yml
Fixes a11y / valid HTML issue where the translation help section has a missing heading.
> Enable title display on translation help block

- config/sync/views.view.services_feed_services_catalogue.yml
- Output loa as raw value (integer)
- Remove theme taxonomy relationship as isn't need and causing duplicates
> Fixes for services catalogue json feed:

- composer.lock
nidirect-site-modules to 2.1.2 contains hotfix for breadcrumbs on embargoed publications
> Update nidirect-site-modules to 2.1.2

- config/sync/block.block.featuredcontent_covid19.yml
Fixes very minor a11y issue / html validation warning
> Add missing section heading for top features on homepage

- config/sync/views.view.pages_with_no_theme.yml
For content types where a theme/subtheme is a mandatory field (articles, publications, application pages, etc), if editors delete a theme then pages tagged with the theme do not display correctly.  This PR creates a content view that lists pages with no theme so that Editors can edit the affected pages and add a theme.
> "Pages with no theme" view config

- composer.json
- composer.lock
Latest release fixes an issue where the cookie banner pops up again immediately after consent has been withdrawn and cookies are not deleted until the user selects reject cookies.  Now when consent is withdrawn, it behaves as if cookies have been rejected - the banner disappears and relevant cookies are deleted.  User is not bothered with another pop-up.
> Update eu_cookie_compliance module to latest release candidate

- config/sync/nidirect_search.solr_elevated_id.probation.yml
- config/sync/nidirect_search.solr_elevated_id.probation_contacts.yml
Elevate content relating to probation so that it appears higher in search results versus content relating to probate.
> D8NID-1545 solr elevations for probation related nodes

- .circleci/config.yml
Once deployed the PLATFORM_PROJECT_ID env var can be removed in Circle CI
> Make platform project id reference the same as the one on psh env vars

- .circleci/config.yml
Can be rebuilt on demand via the UI as drush command broken with PHP 8.1
> Omit taxo entity index rebuild.

- .platform.app.yaml
to prevent the breadcrumbs disappearing ...
> Clear drupal's render cache at 5am every day

- .circleci/config.yml
We have an origins module for creating test accounts now and the QA team have their own automated regression test suite to replace nightwatch from the development phase of the project.
> Omit test account creation and drop functional test PoC

- config/production/fastly.settings.yml
- config/sync/config_split.config_split.production.yml
- config/sync/core.extension.yml
- config/sync/fastly.settings.yml
Fastly should only activate when building/deploying on the detected production environment. It does that by setting the production profile to active in settings.php (detecting a PSH branch env var) and merges the config it finds in that folder with the standard profile. This is how it's done on the Unity and Dept projects so perhaps we had it a bit backwards when we first set this up for NIDirect.
> Move fastly config into production config split to allow it to disable on hosted environments

- config/sync/search_api_autocomplete.search.contacts.yml
- config/sync/search_api_autocomplete.search.health_conditions.yml
- config/sync/search_api_autocomplete.search.search.yml
Increase minimum keyword length to 3 and delay search suggestions by 500ms (instead of default of 300ms)
> D8NID-1574 search autocomplete tweaks

- .platform.app.yaml
There have been a few instances of production exceeding memory quotas and new relic alerts in relation to low apdex.
It may be prudent to optimise PHP-FPM workers - see https://docs.platform.sh/languages/php/fpm.html
Platform sets the request memory for PHP-FPM workers to 45MB by default.  However, it seems that the majority (around 75%) of PHP requests on nidirect production use somewhere between 45MB and 56MB. The default request memory is therefore too low, possibly allows too many concurrent requests, and may be resulting in memory swapping and latencies.
Increase request memory for php-fpm workers from the default of 45 to 56.
> Add sizing hints to .platform.app.yaml for better performance

- .circleci/config.yml
NB nidirect-d8-test-install-profile hasn't been affected
> Use 9.x-dev in favour of legacy development branches

- composer.lock
- config/sync/redirect.settings.yml
Version bump and option that better handles formats such as entity:node/1234 as well as more common /node/1234. If a path alias exists for the canonical path destination, then that is used/applied.
> D8NID-1598 redirect cleanup option

- composer.json
- composer.lock
- web/modules/custom/nidirect_common/nidirect_common.install
Shifting from Listbuilder to the bundled (and maintained) View with Redirect. ListBuilder patch was missing the accessCheck() call required in 9.2+ and I don't want to rely on this patch being updated for any future core changes.
> D8 nid 1623

- composer.json
- composer.lock
Appears to provide a big performance improvement for scheduling transitions on nodes with very large numbers of revisions. Includes prior patch referenced in the composer.json file
> Re-rolled patch for displaying revisions in modal list

- config/sync/webform.webform.prison_visit_online_booking.yml
- web/modules/custom/nidirect_webforms/config/install/webform.webform.prison_visit_online_booking.yml
- web/modules/custom/nidirect_webforms/src/Plugin/WebformHandler/PrisonVisitBookingHandler.php
Alter prison visit booking handler to retrieve all visit slots, face-to-face slots and virtual visit slots, from data posted from PRISM.  (Previously face-to-face slots came from PRISM data and virtual slots were notionally created from config)
Add a submission serial number to emailed form submission to help identify when a submission has not been received.
> Prison visits virtual from json

- config/sync/core.entity_form_display.node.contact.default.yml
- config/sync/core.entity_form_display.node.gp_practice.default.yml
- config/sync/core.entity_view_display.node.driving_instructor.default.yml
- config/sync/core.entity_view_display.node.driving_instructor.full.yml
- config/sync/core.entity_view_display.node.gp_practice.default.yml
- config/sync/core.entity_view_display.node.gp_practice.full.yml
Changed field_telephone to use "NIDirect Telephone Link" formatter as "Telephone Plus" formatter does not exist due to downgrade of telephone_plus module from 2.0@beta to 9.1.
> Update view display config for contact, gp_practice, driving_instructor

- web/themes/custom/nicsdru_nidirect_theme/templates/misc/telephone-plus-item.html.twig
Twig override to:
- output extension prefix as "ext." instead of "x"
- fix issue where supplementary text is output in double brackets
- output a visually hidden title (label) for a number
> Override telephone_plus item twig

- config/sync/core.entity_view_display.node.driving_instructor.teaser.yml
Fixes issue where extra phone: label showing in addition to telephone plus item labels
> Driving instructors teaser display hotfix

- web/modules/custom/nidirect_gp/src/Controller/GpSearchController.php
Catch all possible exceptions when doing reverse location lookup in GpSearchController.php
> Hotfix for GP Practice search WSOD

- .platform.app.yaml
- web/modules/custom/nidirect_breadcrumbs/src/LandingPageBreadcrumb.php
- web/modules/custom/nidirect_breadcrumbs/src/NodeThemesBreadcrumb.php
After many months of disappearing breadcrumb trails, it turns out that an early return in NodeThemesBreadcrumb.php was causing (I think) an empty breadcrumb to be cached with no cache context leading to all nodes then showing an empty breadcrumb after a user views a feature/featured_content_list.
> D8NID-1699 Fix Mysterious Missing Breadcrumb

- web/modules/custom/nidirect_webforms/src/Plugin/WebformHandler/PrisonVisitBookingHandler.php
Fixes issue where if the user makes a face to face booking with additional visitors, and then goes back and changes the booking to a virtual booking, additional visitors were not being removed from the virtual booking.
Also fixed another issue I came across where remembered additional visitor details were being wiped if a user makes a virtual booking immediately after making a face-to-face booking.
> D8NID-812 Prison visits: additional visitors added to a virtual booking
